from .main_page import *
from .login_page import *
from .register_page import *
from .transactions_page import *
from .control_panel_page import *
from .budget_page import *
from .goals_page import *
from .reports_page import *
from .categories_page import *
from .settings_page import *