from .main_page import home_view
from .login_page import login_view
from .register_page import register_view
from .control_panel_page import control_panel_view
from .transactions_page import transactions_view
from .budget_page import budget_view
from .goals_page import goals_view
from .reports_page import reports_view
from .categories_page import categories_view
from .settings_page import settings_view
